talking: "🔊"
whispering: "🔉"
quiet: "🔈"
disabled: "❌" # when the player is connected but e.g. muted
not_installed: "🛠️" # when the player does not have the the mod installed
talk_timeout_ms: 300 # Time in milliseconds after which the talking icon stops. 300 works well for most use cases.